### ISSUE TITLE
Dust bathroom walls and ceiling and scrape flaky paint off ceiling 

### ISSUE THREAD

**Issue by VirgHoskers** [Ferguzz/moving_house#12]

**Comment by VirgHoskers** [comment]
Dear Ferguzz surely the tallest person in the house should duuuuust the ceiling .....?

**Comment by Ferguzz** [comment]
@VirgHoskers stand on a chair ?

**Comment by VirgHoskers** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/9101103-117477752_25-s1-v1.png?transparent=1&palette=1&width=246)
