### ISSUE TITLE
buy bed/sofabed for front room

### ISSUE THREAD

**Issue by Ferguzz** [Ferguzz/moving_house#26]
i'm really into this sofabed by poul volther https://s-media-cache-ak0.pinimg.com/564x/6c/92/65/6c92656a4a24e2d35fd1d10b6ce9719b.jpg

**Comment by Ferguzz** [comment]
how about this ![one](https://cdn1.ykso.co/wildorchid/product/engage-upholstered-sofa-expectation-gray/images/8c19ee8/1490781857/generous.jpg)

**Comment by Ferguzz** [comment]
or dees waan https://www.dotandbo.com/wildorchid/product/remark-sofa-brown?osky_campaign=category-product-grid-home&osky_content=18

**Comment by Ferguzz** [comment]
this one is really similar with a fancy memory foam futon https://www.overstock.com/Home-Garden/Somette-Beli-Mont-Multi-flex-Honey-Oak-Full-size-Wood-Futon-Frame/8884237/product.html

**Comment by Ferguzz** [comment]
thinking our best bet may be a simple platform from the likes of ikea or walmart

**Comment by VirgHoskers** [comment]
I've narrowed it down to the following based on size, price and fitting a trundle bed underneath: 

https://www.wayfair.com/Mercury-Row%C2%AE-Avey-Platform-Bed-MROW8470.html
https://www.wayfair.com/KD-Frames-Charleston-Plus-Platform-Bed-KDFR1012.html
https://www.wayfair.com/Zinus-Quick-Snap-18-Platform-Bed-ZSMT1054.html
https://www.wayfair.com/Zinus-Quick-Snap-14-Platform-Bed-ZSMT1053.html

**Comment by VirgHoskers** [comment]
Trundle: https://www.wayfair.com/KD-Frames-Twin-Trundle-Unit-KDFR1001.html
https://www.wayfair.com/Anew-Edit-Universal-Daybed-Trundle-DRL1574.html
