### ISSUE TITLE
figure out gas and electricity

### ISSUE THREAD

**Issue by Ferguzz** [Ferguzz/moving_house#29]
landlord pays garbage and water

**Comment by VirgHoskers** [comment]
Done!

**Comment by Ferguzz** [comment]
@VirgHoskers can you explain here if there's anything we need to do for this?

**Comment by VirgHoskers** [comment]
There is not.

**Comment by VirgHoskers** [comment]
I've done it.

**Comment by Ferguzz** [comment]
do we just have to start paying or something? how does it work?

can you explain what you did?

**Comment by VirgHoskers** [comment]
I set up an account with PG&E after I asked Peggy what to do. They have us
having a start date of July 1st for our service. Once we start then I will
get emailed about paying the first bill and then I can set up recurring
payments. Seems pretty easy!
