### ISSUE TITLE
change address

### ISSUE THREAD

**Issue by Ferguzz** [Ferguzz/moving_house#31]
TO DO
-------

sfmta?
vets
phone company?
soton council - for next english vote....? 
petco
...tbc

TOM TO DO
------------
natwest
work

DONE
------
ally
amazon
dcu
uscis
usps
metromile
rei
dmv
anthropology
moma
sfbc
aspiration
slc
kaiser

**Comment by VirgHoskers** [comment]
Ooo very neat wan
